# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: macos-latest
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

  #    - uses: actions-ecosystem/action-regex-match@v2
  #      id: regex-match
  #      with:
  #        text: ${{ github.event.release.tag_name }}
  #        # 只匹配稳定版本
  #        regex: '^[vV]?[0-9]+(.[0-9]+)+'
  #    - run: |
  #        echo "regex matched result: (${{ steps.regex-match.outputs.match }})"
      - name: Publish Packages
        id: publish
        uses: gradle/gradle-build-action@v2.4.2
  #      if: ${{ steps.regex-match.outputs.match == github.event.release.tag_name  }}
        with:
          arguments: publishAllPublicationsToOSSRHRepository --info
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          SIGNING_KEY_ID: ${{ secrets.GPG_KEY_ID_SHORT }}
          SIGNING_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          SIGNING_PASSWORD: ${{ secrets.GPG_PASSWORD }}
